name: liq_deployment
on:
  pull_request:
    paths:
      - 'database/**'
 
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: docker://liquibase/liquibase:latest
    - name: Run 'Liquibase status in a Docker Container'
      
      with:
        operation: 'update'
        classpath: './database/tables/'
        changeLogFile: 'databaseChangeLog.xml'
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        url: 'jdbc:postgresql://database-1.cb6fcuuxcjiy.us-east-1.rds.amazonaws.com:5432/postgres'
       



       