name: liq_deployment
on:
  pull_request:
    paths:
      - 'database/**'
 
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Executing liquibase update type create schema
        run: echo "Checking creates folder"
      - uses: liquibase/liquibase-github-action@v7      
        with:
          operation: 'update'
          classpath: './database/tables/'
          changeLogFile: 'databaseChangeLog.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: 'jdbc:postgresql://database-1.cb6fcuuxcjiy.us-east-1.rds.amazonaws.com:5432/postgres'

      - name: Executing liquibase update type data manipulation
        run: echo "Checking data folder"
      - uses: liquibase/liquibase-github-action@v7      
        with:
          operation: 'update'
          classpath: './database/tables/'
          changeLogFile: 'dataChangeLog.xml'
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          url: 'jdbc:postgresql://database-1.cb6fcuuxcjiy.us-east-1.rds.amazonaws.com:5432/postgres'
       



       